nameSuffix: -bch
commonLabels:
  app: stockmarket-simulation-bch
metadata:
  name: stockmarket-simulation-deployment-bch
  namespace: ingress-nginx
bases:
- ../../base
namespace: ingress-nginx
images:
- name: 003718499156.dkr.ecr.us-east-1.amazonaws.com/stockmarket-simulation
  newTag: bch
patchesStrategicMerge:
- stockmarket-simulation-deployment.yaml
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: stockmarket-simulation-deployment-bch
  path: container.yaml