nameSuffix: -brookline-bank
commonLabels:
  app: stockmarket-simulation-brookline-bank
metadata:
  name: stockmarket-simulation-deployment-brookline-bank
  namespace: ingress-nginx
bases:
- ../../base
namespace: ingress-nginx
images:
- name: 003718499156.dkr.ecr.us-east-1.amazonaws.com/stockmarket-simulation
  newTag: brookline-bank
patchesStrategicMerge:
- stockmarket-simulation-deployment-brookline-bank.yaml
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: stockmarket-simulation-deployment-brookline-bank
  path: container.yaml
