apiVersion: v1
kind: Service
metadata:
  name: stockmarket-simulation-service
spec:
  selector:
    app: stockmarket-simulation
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000